sudo: required
services:
  - docker

before_install:
  - docker build -t tlac/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tlac/react-test npm test

after_success:
  - docker build -t tlac/multi-client ./client
  - docker build -t tlac/multi-nginx ./nginx
  - docker build -t tlac/multi-server ./server
  - docker build -t tlac/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and psh them to docker hub
  - docker push tlac/multi-client
  - docker push tlac/multi-nginx
  - docker push tlac/multi-server
  - docker push tlac/multi-worker
